/*
 *  SocialMe Server Project
 *				written by pjc0247
 *	
 *	Protocol definations
 */

#ifndef PROTOCOL_H
#define PROTOCOL_H


enum SocialMeProtocol {

	HELLO = 1,

	LOGIN_TRY,
	LOGIN_INCORRECT,
	LOGIN_DENIED,
	LOGIN_OK,

	LOGOUT_TRY,
	LOGOUT_OK,
	LOGOUT_DENIED,

	REGIST_TRY,
	REGIST_EXIST_ID,
	REGIST_OK,
	REGIST_DENIED,

	USER_QUERY,
	USER_QUERY_IMG,
	USER_QUERY_DENIED,
	USER_INFO,
	USER_INFO_IMG,
	USER_UPDATE,
	USER_UPDATE_OK,
	USER_UPDATE_DENIED,

	FRIEND_QUERY_LIST,
	FRIEND_QUERY_DENIED,

	FOLLOW_FOLLOW,
	FOLLOW_UNFOLLOW,
	FOLLOW_QUERY_FOLLOWING_COUNT,
	FOLLOW_QUERY_FOLLOWED_COUNT,
	FOLLOW_QUERY_FOLLOWING_LIST,
	FOLLOW_QUERY_FOLLOWED_LIST,
	FOLLOW_INFO_FOLLOWING_COUNT,
	FOLLOW_INFO_FOLLOWED_COUNT,
	FOLLOW_INFO_FOLLOWING_LIST,
	FOLLOW_INFO_FOLLOWED_LIST,
	FOLLOW_QUERY_FAILED,

	MESSAGE_PUSH,
	MESSAGE_PUSH_OK,
	MESSAGE_PUSH_FAILED,
	MESSAGE_NOTIFY,
	MESSAGE_QUERY,
	MESSAGE_QUERY_FAILED,
	MESSAGE_INFO,

	PAYMENT_PUSH,
	PAYMENT_PUSH_OK,
	PAYMENT_PUSH_FAILED,
	PAYMENT_QUERY,
	PAYMENT_QUERY_FAILED,
	PAYMENT_SIZE,
	PAYMENT_INFO

	};

#endif // PROTOCOL_H
