/*
 *  SocialMe Server Project
 *				written by pjc0247
 *	
 *	Protocol definations
 */

#ifndef PROTOCOL_H
#define PROTOCOL_H


enum SocialMeProtocol {

	HELLO = 1,
	SERVER_BUSY,

	PING = 100,

	VERSION_CHECK = 200,
	VERSION_OK,
	VERSION_FAILED,

	LOGIN_TRY = 300,
	LOGIN_INCORRECT,
	LOGIN_FAILED,
	LOGIN_OK,

	LOGOUT_TRY = 400,
	LOGOUT_OK,
	LOGOUT_FAILED,

	REGIST_TRY = 500,
	REGIST_EXIST_ID,
	REGIST_OK,
	REGIST_FAILED,

	USER_QUERY = 600,
	USER_QUERY_IMG,
	USER_QUERY_COMMENT,
	USER_QUERY_FAILED,
	USER_INFO,
	USER_INFO_IMG,
	USER_INFO_COMMENT,
	USER_UPDATE,
	USER_UPDATE_COMMENT,
	USER_UPDATE_OK,
	USER_UPDATE_FAILED,
	USER_QUERY_FRIENDS,

	USER_UPDATE_FACEBOOK = 650,
	USER_UPDATE_NATEON,
	USER_QUERY_FACEBOOK,
	USER_QUERY_NATEON,
	USER_INFO_FACEBOOK,
	USER_INFO_NATEON,

	FRIEND_ADD = 700,
	FRIEND_ADD_OK,
	FRIEND_ADD_FAILED,
	FRIEND_ACCEPT,
	FRIEND_DENY,
	FRIEND_OK,
	FRIEND_FAILED,
	FRIEND_DELETE,
	FRIEND_DELETE_OK,
	FRIEND_DELETE_FAILED,
	FRIEND_QUERY_LIST,
	FRIEND_QUERY_FRIEND,
	FRIEND_QUERY_COUNT,
	FRIEND_QUERY_FAILED,
	FRIEND_INFO_LIST,
	FRIEND_INFO_FRIEND,
	FRIEND_INFO_COUNT,

	FOLLOW_FOLLOW = 750,
	FOLLOW_UNFOLLOW,
	FOLLOW_FAILED,
	FOLLOW_OK,
	FOLLOW_QUERY_FOLLOWING,
	FOLLOW_QUERY_FOLLOWED,
	FOLLOW_QUERY_FOLLOWING_COUNT,
	FOLLOW_QUERY_FOLLOWER_COUNT,
	FOLLOW_QUERY_FOLLOWING_LIST,
	FOLLOW_QUERY_FOLLOWER_LIST,
	FOLLOW_INFO_FOLLOWING,
	FOLLOW_INFO_FOLLOWED,
	FOLLOW_INFO_FOLLOWING_COUNT,
	FOLLOW_INFO_FOLLOWER_COUNT,
	FOLLOW_INFO_FOLLOWING_LIST,
	FOLLOW_INFO_FOLLOWER_LIST,
	FOLLOW_QUERY_FAILED,

	LOCATION_PUSH = 800,
	LOCATION_PUSH_FAILED,
	LOCATION_QUERY,
	LOCATION_QUERY_FAILED,
	LOCATION_INFO,

	MESSAGE_PUSH = 900,
	MESSAGE_PUSH_OK,
	MESSAGE_PUSH_FAILED,
	MESSAGE_NOTIFY,
	MESSAGE_NOTIFY_OK,
	MESSAGE_QUERY,
	MESSAGE_QUERY_FAILED,
	MESSAGE_INFO,

	PHOTO_PUSH = 1000,
	PHOTO_OK,
	PHOTO_FAILED,
	PHOTO_DELETE,
	PHOTO_LIKE,
	PHOTO_DISLIKE,
	PHOTO_QUERY,
	PHOTO_QUERY_LIKE,
	PHOTO_QUERY_FAILED,
	PHOTO_INFO,

	PHOTO_COMMENT_PUSH = 1050,
	PHOTO_COMMENT_OK,
	PHOTO_COMMENT_FAILED,
	PHOTO_COMMENT_DELETE,
	PHOTO_COMMENT_QUERY,
	PHOTO_COMMENT_QUERY_FAILED,
	PHOTO_COMMENT_INFO,

	POST_INC = 1100,
	POST_DEC,
	POST_QUERY_COUNT,
	POST_OK,
	POST_FAILED,
	POST_QUERY_FAILED,
	POST_INFO_COUNT,

	PAYMENT_PUSH = 1200,
	PAYMENT_PUSH_OK,
	PAYMENT_PUSH_FAILED,
	PAYMENT_QUERY,
	PAYMENT_QUERY_FAILED,
	PAYMENT_SIZE,
	PAYMENT_INFO,

	PACKET_UNKNOWN = 9999

	};

#endif // PROTOCOL_H
