#ifndef SERVER_CONFIG_H
#define SERVER_CONFIG_H

#define SERVER_PORT				9919

#define SERVER_LISTEN_QUEUE		100

#define SERVER_VERSION_MAJOR	0
#define SERVER_VERSION_MINOR	1
#define SERVER_VERSION_FIX		0

#endif // SERVER_CONFIG_H